"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function CreateShopPage() {
  const router = useRouter();
  const [form, setForm] = useState({ name: "", description: "", address: "", phone: "", email: "", website: "" });
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  function update(key: string, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); const response = await fetch("/api/shops", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "Could not create Virtual Store."); setBusy(false); return; } router.push("/profile/shops"); }
  return <div className="mx-auto max-w-2xl px-4 py-10 sm:px-6"><p className="text-sm font-medium text-brand">Virtual Store</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Create a Virtual Store</h1><p className="mt-2 text-sm text-slate-500">Your storefront will remain private until the required subscription is active. Subscription: <span className="font-semibold text-brand">R59 per month</span>.</p><div className="mt-4 rounded-md border border-brand/20 bg-brand/5 px-3 py-2 text-sm text-slate-700">Public storefronts require an active R59/month subscription.</div><form onSubmit={submit} className="mt-8 space-y-5"><Field label="Store name" value={form.name} onChange={(value) => update("name", value)} /><label className="block text-sm font-medium">Store description<textarea required minLength={10} rows={5} value={form.description} onChange={(event) => update("description", event.target.value)} className="mt-1 w-full rounded-md border border-border p-3 text-sm outline-none focus:border-brand" /></label><Field label="Store location or trading area" value={form.address} onChange={(value) => update("address", value)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Phone" value={form.phone} required={false} onChange={(value) => update("phone", value)} /><Field label="Email" type="email" value={form.email} required={false} onChange={(value) => update("email", value)} /></div><Field label="Website" type="url" value={form.website} required={false} onChange={(value) => update("website", value)} />{error && <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-md bg-brand px-4 py-3 text-sm font-semibold text-white hover:bg-brand-dark disabled:opacity-60">{busy ? "Submitting..." : "Create Virtual Store"}</button></form></div>;
}
function Field({ label, value, onChange, type = "text", required = true }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block text-sm font-medium">{label}<input type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-md border border-border p-2.5 text-sm outline-none focus:border-brand" /></label>; }
