import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { formatZAR } from "@/lib/utils";
import { OwnedContentActions } from "@/components/account/owned-content-actions";

export const dynamic = "force-dynamic";
export default async function MyPropertiesPage() { const session = await auth(); if (!session?.user) redirect("/login?callbackUrl=/profile/properties"); const properties = await prisma.propertyListing.findMany({ where: { ownerId: session.user.id, status: { not: "REMOVED" } }, orderBy: { updatedAt: "desc" } }); return <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">My properties</h1><p className="mt-2 text-sm text-slate-500">Manage property listings you have submitted.</p></div><Link href="/real-estate/new" className="rounded-md bg-brand px-4 py-2 text-sm font-semibold text-white">List property</Link></div><div className="mt-8 overflow-hidden rounded-lg border border-border bg-white">{properties.length === 0 ? <p className="px-6 py-14 text-center text-sm text-slate-500">No properties yet.</p> : properties.map((property) => <div key={property.id} className="flex items-center justify-between gap-4 border-b border-border p-5 last:border-0"><div className="min-w-0"><p className="truncate font-medium">{property.title}</p><p className="mt-1 text-sm text-slate-500">{property.listingType === "FOR_SALE" ? "For sale" : "For rent"} · {formatZAR(property.priceCents)} · {property.location}</p><p className="mt-1 text-xs text-slate-400">{property.status.replaceAll("_", " ")}</p></div><div className="flex shrink-0 items-center gap-3">{property.status === "ACTIVE" && <Link href={`/real-estate/${property.slug}`} className="text-xs font-medium text-brand">View</Link>}<OwnedContentActions type="properties" id={property.id} /></div></div>)}</div></div>; }
