import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { formatZAR } from "@/lib/utils";
import { SubmissionReviewControl } from "@/components/admin/submission-review-control";

export const dynamic = "force-dynamic";

export default async function ModerationPage() {
  const session = await auth();
  if (!session?.user || !["ADMIN", "MODERATOR"].includes(session.user.role)) redirect("/");
  const [listings, shops, services, properties] = await Promise.all([
    prisma.listing.findMany({ where: { status: "PENDING_REVIEW" }, orderBy: { createdAt: "asc" }, include: { seller: { select: { username: true } }, category: { select: { name: true } }, images: { take: 1, orderBy: { sortOrder: "asc" } } } }),
    prisma.shop.findMany({ where: { status: "PENDING_REVIEW" }, orderBy: { createdAt: "asc" }, include: { owner: { select: { username: true } } } }),
    prisma.serviceListing.findMany({ where: { status: "PENDING_REVIEW" }, orderBy: { createdAt: "asc" }, include: { provider: { select: { username: true } }, category: { select: { name: true } } } }),
    prisma.propertyListing.findMany({ where: { status: "PENDING_REVIEW" }, orderBy: { createdAt: "asc" }, include: { owner: { select: { username: true } } } }),
  ]);
  const total = listings.length + shops.length + services.length + properties.length;
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-brand">Admin moderation</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Pending submissions</h1><p className="mt-2 text-sm text-slate-500">Review content before it appears publicly.</p></div><span className="text-sm font-medium text-slate-500">{total} pending</span></div>{total === 0 ? <div className="mt-8 rounded-lg border border-dashed border-border px-6 py-16 text-center"><p className="font-medium">Queue is clear</p><p className="mt-1 text-sm text-slate-500">There are no submissions awaiting review.</p></div> : <div className="mt-8 space-y-8">{listings.length > 0 && <QueueGroup title="Products">{listings.map((item) => <ReviewCard key={item.id} targetType="LISTING" targetId={item.id} title={item.title} summary={`${item.category.name} · ${formatZAR(item.priceCents)} · ${item.condition.replaceAll("_", " ")}`} description={item.description} username={item.seller.username} createdAt={item.createdAt} imageUrl={item.images[0]?.url} />)}</QueueGroup>}{shops.length > 0 && <QueueGroup title="Shops">{shops.map((item) => <ReviewCard key={item.id} targetType="SHOP" targetId={item.id} title={item.name} summary={item.address} description={item.description} username={item.owner.username} createdAt={item.createdAt} />)}</QueueGroup>}{services.length > 0 && <QueueGroup title="Services">{services.map((item) => <ReviewCard key={item.id} targetType="SERVICE" targetId={item.id} title={item.title} summary={`${item.category.name} · ${item.serviceArea}`} description={item.description} username={item.provider.username} createdAt={item.createdAt} />)}</QueueGroup>}{properties.length > 0 && <QueueGroup title="Properties">{properties.map((item) => <ReviewCard key={item.id} targetType="PROPERTY" targetId={item.id} title={item.title} summary={`${item.listingType === "FOR_SALE" ? "For sale" : "For rent"} · ${item.propertyType.replaceAll("_", " ")} · ${formatZAR(item.priceCents)}`} description={item.description} username={item.owner.username} createdAt={item.createdAt} />)}</QueueGroup>}</div>}</div>;
}

function QueueGroup({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3 space-y-3">{children}</div></section>; }
function ReviewCard({ targetType, targetId, title, summary, description, username, createdAt, imageUrl }: { targetType: "LISTING" | "SHOP" | "SERVICE" | "PROPERTY"; targetId: string; title: string; summary: string; description: string; username: string; createdAt: Date; imageUrl?: string }) { return <article className="flex flex-col gap-4 rounded-lg border border-border bg-white p-5 sm:flex-row sm:items-start">{imageUrl && <img src={imageUrl} alt="" className="h-20 w-20 rounded-md object-cover" />}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{title}</h3><span className="rounded-full bg-amber-50 px-2 py-0.5 text-[11px] font-medium text-amber-800">Pending</span></div><p className="mt-1 text-xs font-medium text-brand">{summary}</p><p className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{description}</p><p className="mt-3 text-xs text-slate-400">Submitted by @{username} · {createdAt.toLocaleString("en-ZA")}</p></div><SubmissionReviewControl targetType={targetType} targetId={targetId} /></article>; }
