import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { formatZAR } from "@/lib/utils";
import { OwnedContentActions } from "@/components/account/owned-content-actions";

export const dynamic = "force-dynamic";
export default async function MyServicesPage() { const session = await auth(); if (!session?.user) redirect("/login?callbackUrl=/profile/services"); const services = await prisma.serviceListing.findMany({ where: { providerId: session.user.id, status: { not: "REMOVED" } }, orderBy: { updatedAt: "desc" }, include: { category: { select: { name: true } } } }); return <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">My services</h1><p className="mt-2 text-sm text-slate-500">Manage service profiles you have submitted.</p></div><Link href="/services/new" className="rounded-md bg-brand px-4 py-2 text-sm font-semibold text-white">Offer a service</Link></div><div className="mt-8 overflow-hidden rounded-lg border border-border bg-white">{services.length === 0 ? <p className="px-6 py-14 text-center text-sm text-slate-500">No service profiles yet.</p> : services.map((service) => <div key={service.id} className="flex items-center justify-between gap-4 border-b border-border p-5 last:border-0"><div className="min-w-0"><p className="truncate font-medium">{service.title}</p><p className="mt-1 text-sm text-slate-500">{service.category.name} · {service.priceCents == null ? "Quote" : formatZAR(service.priceCents)}</p><p className="mt-1 text-xs text-slate-400">{service.status.replaceAll("_", " ")}</p></div><div className="flex shrink-0 items-center gap-3">{service.status === "ACTIVE" && <Link href={`/services/${service.slug}`} className="text-xs font-medium text-brand">View</Link>}<OwnedContentActions type="services" id={service.id} /></div></div>)}</div></div>; }
